package com.gwang.techforum4.rules;

import com.gwang.techforum4.models.Person
import com.gwang.techforum4.models.IsFather
import com.gwang.techforum4.models.IsGrandpa

dialect  "mvel"

rule "Father's father is a grandpa"
    when
        IsFather($p1 : f, $p2 : s)
        IsFather(f == $p1, $p3: s)
    then
        System.out.println("Inferred " + $p1.getName() + " is " + $p3.getName() + "'s grandpa.");
        insertLogical(new IsGrandpa($p1, $p3))
end

rule "Grandpa likes to give candies to his grandson"
    when
        IsGrandpa($p1 : gf, $p2 : gs)
    then
        System.out.println("Grandpa " + $p1.getName() + " gives " + $p1.getCandy() + "candies to grandson " + $p2.getName());
        modify($p2) { setCandy($p1.candy + $p2.candy)}
        modify($p1) { setCandy(0)}
    end
